const { PrismaClient } = require('@prisma/client')
const p = new PrismaClient()
async function main() {
    const q = await p.$queryRawUnsafe(`SELECT status, COUNT(*)::int as c FROM "EmailQueue" WHERE type='survey_campaign' GROUP BY status ORDER BY c DESC`)
    console.log('Queue by status:', JSON.stringify(q))
    const logSuccess = await p.emailLog.count({ where: { type: 'survey_campaign', success: true } })
    const queueTotal = await p.emailQueue.count({ where: { type: 'survey_campaign' } })
    const queueSent = await p.emailQueue.count({ where: { type: 'survey_campaign', status: 'sent' } })
    console.log(`EmailLog success: ${logSuccess}`)
    console.log(`Queue total: ${queueTotal}, Queue status=sent: ${queueSent}`)
    console.log(`Dashboard shows: ${queueSent} of ${queueTotal} = ${Math.round(queueSent/queueTotal*100)}%`)
    console.log(`\nThe "100% sent" bug: if total=sent because failed were reset to pending, and pending aren't counted differently...`)
    await p.$disconnect()
}
main().catch(e => { console.error(e); process.exit(1) })
