const fs = require('fs');

const translations = {
  es: { codeSent:'Se ha enviado un código de 6 dígitos a tu correo. Revisa tu bandeja de entrada y spam.', emailNotConfigured:'El envío de correos aún no está configurado. Contacta al administrador.', enterAllDigits:'Por favor ingresa los 6 dígitos.', invalidCode:'Código inválido', sendingCode:'Enviando un nuevo código...', newCodeSent:'¡Se ha enviado un nuevo código!', resendFailed:'No se pudo reenviar el código. Inténtalo más tarde.', codeExpiresIn:'El código expira en', enterVerificationCode:'Ingresa el código de verificación', weSentCode:'Enviamos un código a {email}', enterYourCode:'Ingresa tu código de verificación de 6 dígitos', resendCode:'¿No recibiste el código? Reenviar', verifyCodeBtn:'Verificar código', pwWeak:'Débil', pwFair:'Regular', pwGood:'Buena', pwStrong:'Fuerte', pwExcellent:'Excelente' },
  fr: { codeSent:"Un code à 6 chiffres a été envoyé à votre adresse e-mail. Vérifiez votre boîte de réception et les spams.", emailNotConfigured:"L'envoi d'e-mails n'est pas encore configuré. Contactez l'administrateur.", enterAllDigits:'Veuillez saisir les 6 chiffres.', invalidCode:'Code invalide', sendingCode:"Envoi d'un nouveau code...", newCodeSent:'Un nouveau code a été envoyé !', resendFailed:'Impossible de renvoyer le code. Réessayez plus tard.', codeExpiresIn:'Le code expire dans', enterVerificationCode:'Entrez le code de vérification', weSentCode:'Nous avons envoyé un code à {email}', enterYourCode:'Entrez votre code de vérification à 6 chiffres', resendCode:"Vous n'avez pas reçu le code ? Renvoyer", verifyCodeBtn:'Vérifier le code', pwWeak:'Faible', pwFair:'Passable', pwGood:'Bien', pwStrong:'Fort', pwExcellent:'Excellent' },
  ar: { codeSent:'تم إرسال رمز مكوّن من 6 أرقام إلى بريدك الإلكتروني. تحقق من صندوق الوارد والبريد العشوائي.', emailNotConfigured:'لم يتم إعداد إرسال البريد الإلكتروني بعد. يرجى التواصل مع المسؤول.', enterAllDigits:'يرجى إدخال جميع الأرقام الستة.', invalidCode:'رمز غير صالح', sendingCode:'جارٍ إرسال رمز جديد...', newCodeSent:'تم إرسال رمز جديد!', resendFailed:'فشل إعادة إرسال الرمز. حاول مرة أخرى لاحقاً.', codeExpiresIn:'ينتهي الرمز خلال', enterVerificationCode:'أدخل رمز التحقق', weSentCode:'أرسلنا رمزاً إلى {email}', enterYourCode:'أدخل رمز التحقق المكوّن من 6 أرقام', resendCode:'لم تستلم الرمز؟ إعادة الإرسال', verifyCodeBtn:'التحقق من الرمز', pwWeak:'ضعيفة', pwFair:'مقبولة', pwGood:'جيدة', pwStrong:'قوية', pwExcellent:'ممتازة' },
  zh: { codeSent:'一个6位验证码已发送至您的邮箱。请检查收件箱和垃圾邮件文件夹。', emailNotConfigured:'邮件发送功能尚未配置。请联系管理员。', enterAllDigits:'请输入全部6位数字。', invalidCode:'验证码无效', sendingCode:'正在发送新验证码...', newCodeSent:'新验证码已发送！', resendFailed:'重新发送失败，请稍后再试。', codeExpiresIn:'验证码将在以下时间后过期', enterVerificationCode:'输入验证码', weSentCode:'我们已向 {email} 发送验证码', enterYourCode:'请输入6位验证码', resendCode:'没有收到验证码？重新发送', verifyCodeBtn:'验证码确认', pwWeak:'弱', pwFair:'一般', pwGood:'良好', pwStrong:'强', pwExcellent:'极强' },
  hi: { codeSent:'आपके ईमेल पर 6 अंकों का कोड भेजा गया है। अपना इनबॉक्स और स्पैम फ़ोल्डर जांचें।', emailNotConfigured:'ईमेल भेजना अभी कॉन्फ़िगर नहीं है। कृपया एडमिन से संपर्क करें।', enterAllDigits:'कृपया सभी 6 अंक दर्ज करें।', invalidCode:'अमान्य कोड', sendingCode:'नया कोड भेजा जा रहा है...', newCodeSent:'एक नया कोड भेजा गया है!', resendFailed:'कोड पुनः भेजने में विफल। बाद में पुनः प्रयास करें।', codeExpiresIn:'कोड समाप्त होता है', enterVerificationCode:'सत्यापन कोड दर्ज करें', weSentCode:'हमने {email} पर कोड भेजा', enterYourCode:'अपना 6 अंकों का सत्यापन कोड दर्ज करें', resendCode:'कोड नहीं मिला? पुनः भेजें', verifyCodeBtn:'कोड सत्यापित करें', pwWeak:'कमज़ोर', pwFair:'ठीक है', pwGood:'अच्छा', pwStrong:'मज़बूत', pwExcellent:'उत्कृष्ट' },
  pt: { codeSent:'Um código de 6 dígitos foi enviado ao seu e-mail. Verifique sua caixa de entrada e spam.', emailNotConfigured:'O envio de e-mails ainda não está configurado. Entre em contato com o administrador.', enterAllDigits:'Por favor, insira todos os 6 dígitos.', invalidCode:'Código inválido', sendingCode:'Enviando um novo código...', newCodeSent:'Um novo código foi enviado!', resendFailed:'Falha ao reenviar o código. Tente novamente mais tarde.', codeExpiresIn:'Código expira em', enterVerificationCode:'Digite o código de verificação', weSentCode:'Enviamos um código para {email}', enterYourCode:'Digite seu código de verificação de 6 dígitos', resendCode:'Não recebeu o código? Reenviar', verifyCodeBtn:'Verificar código', pwWeak:'Fraca', pwFair:'Razoável', pwGood:'Boa', pwStrong:'Forte', pwExcellent:'Excelente' },
  ru: { codeSent:'6-значный код отправлен на ваш email. Проверьте входящие и папку со спамом.', emailNotConfigured:'Отправка email пока не настроена. Обратитесь к администратору.', enterAllDigits:'Пожалуйста, введите все 6 цифр.', invalidCode:'Неверный код', sendingCode:'Отправляем новый код...', newCodeSent:'Новый код отправлен!', resendFailed:'Не удалось отправить код повторно. Попробуйте позже.', codeExpiresIn:'Код истекает через', enterVerificationCode:'Введите код подтверждения', weSentCode:'Мы отправили код на {email}', enterYourCode:'Введите 6-значный код подтверждения', resendCode:'Не получили код? Отправить повторно', verifyCodeBtn:'Подтвердить код', pwWeak:'Слабый', pwFair:'Средний', pwGood:'Хороший', pwStrong:'Сильный', pwExcellent:'Отличный' },
  ja: { codeSent:'6桁のコードをメールに送信しました。受信トレイとスパムフォルダをご確認ください。', emailNotConfigured:'メール送信はまだ設定されていません。管理者にお問い合わせください。', enterAllDigits:'6桁すべてを入力してください。', invalidCode:'無効なコード', sendingCode:'新しいコードを送信中...', newCodeSent:'新しいコードが送信されました！', resendFailed:'コードの再送信に失敗しました。後でもう一度お試しください。', codeExpiresIn:'コードの有効期限', enterVerificationCode:'確認コードを入力', weSentCode:'{email} にコードを送信しました', enterYourCode:'6桁の確認コードを入力してください', resendCode:'コードが届かない場合は再送信', verifyCodeBtn:'コードを確認', pwWeak:'弱い', pwFair:'普通', pwGood:'良い', pwStrong:'強い', pwExcellent:'非常に強い' },
  de: { codeSent:'Ein 6-stelliger Code wurde an Ihre E-Mail gesendet. Prüfen Sie Ihren Posteingang und Spam-Ordner.', emailNotConfigured:'Der E-Mail-Versand ist noch nicht konfiguriert. Bitte wenden Sie sich an den Administrator.', enterAllDigits:'Bitte geben Sie alle 6 Ziffern ein.', invalidCode:'Ungültiger Code', sendingCode:'Sende neuen Code...', newCodeSent:'Ein neuer Code wurde gesendet!', resendFailed:'Code konnte nicht erneut gesendet werden. Bitte versuchen Sie es später.', codeExpiresIn:'Code läuft ab in', enterVerificationCode:'Bestätigungscode eingeben', weSentCode:'Wir haben einen Code an {email} gesendet', enterYourCode:'Geben Sie Ihren 6-stelligen Bestätigungscode ein', resendCode:'Keinen Code erhalten? Erneut senden', verifyCodeBtn:'Code bestätigen', pwWeak:'Schwach', pwFair:'Mäßig', pwGood:'Gut', pwStrong:'Stark', pwExcellent:'Ausgezeichnet' },
  ko: { codeSent:'6자리 코드가 이메일로 전송되었습니다. 받은 편지함과 스팸 폴더를 확인하세요.', emailNotConfigured:'이메일 전송이 아직 구성되지 않았습니다. 관리자에게 문의하세요.', enterAllDigits:'6자리를 모두 입력해 주세요.', invalidCode:'잘못된 코드', sendingCode:'새 코드를 전송 중...', newCodeSent:'새 코드가 전송되었습니다!', resendFailed:'코드 재전송에 실패했습니다. 나중에 다시 시도하세요.', codeExpiresIn:'코드 만료 시간', enterVerificationCode:'인증 코드 입력', weSentCode:'{email}로 코드를 전송했습니다', enterYourCode:'6자리 인증 코드를 입력하세요', resendCode:'코드를 받지 못하셨나요? 재전송', verifyCodeBtn:'코드 확인', pwWeak:'매우 약함', pwFair:'보통', pwGood:'양호', pwStrong:'강함', pwExcellent:'매우 강함' }
};

let updated = 0;
for (const [locale, keys] of Object.entries(translations)) {
  const lPath = 'src/messages/' + locale + '.json';
  const lJson = JSON.parse(fs.readFileSync(lPath, 'utf8'));
  if (!lJson.forgotPassword) lJson.forgotPassword = {};
  Object.assign(lJson.forgotPassword, keys);
  fs.writeFileSync(lPath, JSON.stringify(lJson, null, 2));
  updated++;
  console.log('Updated ' + locale + '.json');
}
console.log('Done: ' + updated + ' locales');
